# Generated by Django 4.2.20 on 2025-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DESCRICAO'),
        ),
    ]
