# Generated by Django 4.2.20 on 2025-05-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=200)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('convidados', models.TextField(blank=True, null=True)),
                ('local', models.URLField(default='https://')),
                ('descricao', models.TextField(default='')),
            ],
        ),
    ]
