# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Aguardando PostgreSQL iniciar..."
            sleep 1
          done
          
      - name: Lint with flake8
        run: flake8
        
      - name: Test with pytest
        env:
          POSTGRES_DB: tesdata_base
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DB_HOST: localhost
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tesdata_base
        run: pytest
        